version: '3.8'

services:
  userService:
    image: user_service:v1
    restart: always
    ports:
      - 8080:8080
    environment:
      MYSQL_URL: jdbc:mysql://userdb:3306/microservice-user
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: 123
      EUREKA_URL:
    depends_on:
      - userdb

  userdb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: microservice-user
    volumes:
      - mysql-user-data:/var/lib/mysql

volumes:
  mysql-user-data: