server:
  port: 8081
spring:
  application:
    name: department-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/microservice-user}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:}
  jpa:
    hibernate:
      ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
