server:
  port: 8080

spring:
  application:
    name: user-service
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/microservice-user}
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_USERNAME:}

  jpa:
    hibernate:
      ddl-auto: update

  cache:
    type: redis
    redis:
      time-to-live: 60000

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
